### ISSUE TITLE
Rda as data format

### ISSUE THREAD

**Issue by tmalsburg** [vasishth/VasishthLab#1]
Like you, I often use R's binary Rda format for storing data.  The benefit is that it's compact and you get out exactly what you put in.  The latter is not necessarily the case with CSV files.  For example, a factor is indistinguishable from a character vector in CSV and you lose extra information in factors such as the contrast coding.  However, Rda has one important draw-back for the current purpose: it's not necessarily future-proof.  The format has historically changed and when that happens it's really annoying for users because they have to install older versions of R to read the data.  CSV and similar formats (I prefer tab-separated values) will of course always be readable, not just with R but also with a wide range of other programs like Excel et al.

**Comment by vasishth** [comment]
Agreed. I got into trouble with Hadley Wickham for wanting to store text files as data in a package. I have had the exact problem you describe, and for my own data---I couldn't read it any more after a few years. I will back off to simple text data as you suggest.

**Comment by vasishth** [comment]
However, stan precomputed data will have to remain in Rda format, it is too large to be stored any other way. I may also compress it in future. But this is OK because I will provide code for regenerating this data in my vignettes.

**Comment by tmalsburg** [comment]
There are efforts to develop a robust cross-platform format but that is in early stages and I think limited to data.frames.  So that's not really a solution.

**Comment by tmalsburg** [comment]
Another consideration: not everyone is using R and I think that research data should be readable for everyone not just for R hackers.  Most of us may be using Julia a couple of years down the line and all those Rda files may be a huge annoyance then.  Of course someone may write a Julia package for reading Rda but R's data types do not map to Julia's 1-to-1 so this will not work without problems.
